services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    env_file:
      - ./compose/aws.env
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
    restart: always

  ai-rag-chatbot-backend:
    build:
      context: .
      target: development
    image: ai-rag-chatbot-backend-development
    container_name: ai-rag-chatbot-backend-development
    ports:
      - 8085:8085
    links:
      - "localstack:localstack"
      - "mongodb:mongodb"
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - ./compose/aws.env
    environment:
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
    develop:
      watch:
        - action: sync
          path: ./app
          target: /home/python/app/app
          ignore:
            - README.md
            - "**/*.md"
            - "**/test_*.py"
            - tests/**/*
            - .git/**/*
            - .venv/**/*
            - .pytest_cache/**/*
            - .ruff_cache/**/*
            - .vscode/**/*
            - .github/**/*
            - requirements-dev.txt
            - pytest.ini
            - .pre-commit-config.yaml
            - sonar-project.properties
            - LICENCE
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge

